"""Seller tool: create the Ed25519 signing keypair and (optionally) wire the
public key + server URL into the customer application.

    python license_server/keygen.py --private-out ~/secrets/license_private.key \
        --write-constants app/licensing/constants.py --server-url https://license.example.com

The PRIVATE key is written to a file with owner-only permissions. Never commit it,
never put it in the customer package.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from signing import generate_keypair  # noqa: E402

_CONSTANTS_TEMPLATE = '''"""Seller-set license constants (generated by license_server/keygen.py)."""

PRODUCT_ID = "{product}"
LICENSE_SERVER_URL = "{url}"
LICENSE_PUBLIC_KEY = "{public}"
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--private-out", required=True, help="where to store the PRIVATE key (outside the repo!)")
    parser.add_argument("--write-constants", help="path of app/licensing/constants.py to update")
    parser.add_argument("--server-url", default="", help="public https URL of your license server")
    parser.add_argument("--product", default="telegram-auto-poster")
    args = parser.parse_args()

    out = Path(args.private_out).expanduser()
    if out.exists():
        print(f"Refusing to overwrite existing key file: {out}", file=sys.stderr)
        return 1
    private, public = generate_keypair()
    out.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(private + "\n")
    print(f"Private key written to {out} (keep it secret, back it up).")
    print(f"Public key: {public}")
    if args.write_constants:
        Path(args.write_constants).write_text(
            _CONSTANTS_TEMPLATE.format(product=args.product, url=args.server_url, public=public),
            encoding="utf-8",
        )
        print(f"Updated {args.write_constants}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
