-- Telegram Auto Poster: initial schema.
-- Written in the portable subset of SQL that PostgreSQL and SQLite both accept,
-- so the same file is verified by the offline test-suite and run in production
-- on PostgreSQL. Identifiers (UUID) are generated by the application.
--
-- Cross-user isolation is enforced by the database: child rows carry user_id and
-- reference their parents through composite (id, user_id) foreign keys, so a
-- schedule of user B can never point at a post or group of user A.

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    display_name  TEXT,
    is_admin      BOOLEAN NOT NULL DEFAULT FALSE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    timezone      TEXT NOT NULL DEFAULT 'UTC',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX users_email_lower_uq ON users (lower(email));

CREATE TABLE telegram_accounts (
    id           UUID PRIMARY KEY,
    user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tg_user_id   BIGINT NOT NULL,
    username     TEXT,
    first_name   TEXT,
    phone_masked TEXT,
    status       TEXT NOT NULL DEFAULT 'connected'
                 CHECK (status IN ('connected', 'disconnected', 'session_expired', 'revoked')),
    connected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, user_id),
    UNIQUE (user_id, tg_user_id)
);

-- Telegram session material is stored ONLY encrypted (Fernet), see app/security/crypto.py.
CREATE TABLE telegram_sessions (
    id           UUID PRIMARY KEY,
    account_id   UUID NOT NULL UNIQUE REFERENCES telegram_accounts (id) ON DELETE CASCADE,
    session_enc  TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'expired', 'revoked')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ
);

CREATE TABLE telegram_groups (
    id                    UUID PRIMARY KEY,
    user_id               UUID NOT NULL,
    account_id            UUID NOT NULL,
    tg_chat_id            BIGINT NOT NULL,
    title                 TEXT NOT NULL,
    username              TEXT,
    chat_type             TEXT NOT NULL
                          CHECK (chat_type IN ('group', 'supergroup', 'channel', 'forum')),
    permission_status     TEXT NOT NULL DEFAULT 'unknown'
                          CHECK (permission_status IN ('unknown', 'ok', 'no_permission', 'unavailable', 'restricted')),
    permission_detail     TEXT,
    permission_checked_at TIMESTAMPTZ,
    is_enabled            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, user_id),
    UNIQUE (account_id, tg_chat_id),
    FOREIGN KEY (account_id, user_id) REFERENCES telegram_accounts (id, user_id) ON DELETE CASCADE
);

CREATE TABLE posts (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      TEXT,
    body       TEXT NOT NULL,
    media      JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, user_id)
);

CREATE TABLE schedules (
    id               UUID PRIMARY KEY,
    user_id          UUID NOT NULL,
    post_id          UUID NOT NULL,
    account_id       UUID NOT NULL,
    kind             TEXT NOT NULL CHECK (kind IN ('once', 'daily', 'weekly', 'custom')),
    timezone         TEXT NOT NULL,
    run_at           TIMESTAMPTZ,
    times_of_day     JSONB NOT NULL DEFAULT '[]',
    days_of_week     JSONB NOT NULL DEFAULT '[]',
    interval_minutes INTEGER CHECK (interval_minutes IS NULL OR interval_minutes >= 1),
    starts_at        TIMESTAMPTZ,
    ends_at          TIMESTAMPTZ,
    status           TEXT NOT NULL DEFAULT 'active'
                     CHECK (status IN ('active', 'paused', 'completed')),
    next_run_at      TIMESTAMPTZ,
    last_run_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, user_id),
    FOREIGN KEY (post_id, user_id) REFERENCES posts (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (account_id, user_id) REFERENCES telegram_accounts (id, user_id) ON DELETE CASCADE
);
CREATE INDEX schedules_next_run_idx ON schedules (next_run_at) WHERE status = 'active';

CREATE TABLE schedule_targets (
    schedule_id UUID NOT NULL,
    group_id    UUID NOT NULL,
    user_id     UUID NOT NULL,
    PRIMARY KEY (schedule_id, group_id),
    FOREIGN KEY (schedule_id, user_id) REFERENCES schedules (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (group_id, user_id) REFERENCES telegram_groups (id, user_id) ON DELETE CASCADE
);

-- One row per (schedule occurrence, group). Workers claim rows with
-- SELECT ... FOR UPDATE SKIP LOCKED. Snapshots keep history readable after the
-- schedule or group is deleted.
CREATE TABLE posting_jobs (
    id                   UUID PRIMARY KEY,
    user_id              UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    schedule_id          UUID REFERENCES schedules (id) ON DELETE SET NULL,
    account_id           UUID NOT NULL REFERENCES telegram_accounts (id) ON DELETE CASCADE,
    group_id             UUID REFERENCES telegram_groups (id) ON DELETE SET NULL,
    group_title          TEXT NOT NULL,
    text_snapshot        TEXT NOT NULL,
    media_snapshot       JSONB NOT NULL DEFAULT '[]',
    scheduled_for        TIMESTAMPTZ NOT NULL,
    status               TEXT NOT NULL DEFAULT 'scheduled'
                         CHECK (status IN ('scheduled', 'processing', 'waiting', 'posted', 'failed', 'cancelled')),
    attempts             INTEGER NOT NULL DEFAULT 0,
    max_attempts         INTEGER NOT NULL DEFAULT 5,
    next_attempt_at      TIMESTAMPTZ NOT NULL,
    locked_by            TEXT,
    lease_expires_at     TIMESTAMPTZ,
    send_started_at      TIMESTAMPTZ,
    idempotency_key      TEXT NOT NULL UNIQUE,
    error_code           TEXT,
    error_message        TEXT,
    telegram_message_ids JSONB,
    posted_at            TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX posting_jobs_due_idx ON posting_jobs (next_attempt_at)
    WHERE status IN ('scheduled', 'waiting');
CREATE INDEX posting_jobs_lease_idx ON posting_jobs (lease_expires_at)
    WHERE status = 'processing';
CREATE INDEX posting_jobs_user_idx ON posting_jobs (user_id, scheduled_for DESC);

CREATE TABLE posting_logs (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    job_id     UUID REFERENCES posting_jobs (id) ON DELETE SET NULL,
    level      TEXT NOT NULL CHECK (level IN ('info', 'warning', 'error')),
    event      TEXT NOT NULL,
    message    TEXT NOT NULL,
    details    JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX posting_logs_user_idx ON posting_logs (user_id, created_at DESC);
CREATE INDEX posting_logs_job_idx ON posting_logs (job_id);

CREATE TABLE settings (
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    key        TEXT NOT NULL,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, key)
);

-- Installation-wide key/value state (e.g. the generated installation_id).
CREATE TABLE app_state (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- The single local license activation (always row id = 1). Times are unix seconds.
CREATE TABLE license_activation (
    id              SMALLINT PRIMARY KEY CHECK (id = 1),
    license_key_enc TEXT NOT NULL,
    license_id      TEXT NOT NULL,
    product         TEXT NOT NULL,
    installation_id TEXT NOT NULL,
    host            TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL,
    payload_json    TEXT NOT NULL,
    signature       TEXT NOT NULL,
    activated_at    BIGINT NOT NULL,
    last_verified_at BIGINT NOT NULL,
    last_attempt_at BIGINT,
    last_error      TEXT,
    high_water_at   BIGINT NOT NULL,
    updated_at      BIGINT NOT NULL
);
