-- Step 5: post drafts, one optional image per post, and per-post target groups.
-- The posts table (migration 0001) already exists and is EXTENDED here, never recreated. Written in the portable SQL
-- subset (PostgreSQL + SQLite) like all other migrations.
--
-- Ownership: every child row carries user_id AND account_id and references its parents through composite foreign keys,
-- so the database itself refuses a target group of another user or of another Telegram account, and an image row that
-- points at somebody else's post. posts.account_id is a plain foreign key to telegram_accounts(id): a composite
-- (account_id, user_id) key cannot be added to an existing table in the portable subset, so that one pairing is checked by
-- the service layer (every query is scoped by user_id and account_id) and, for every target, by post_targets below.

ALTER TABLE posts ADD COLUMN account_id UUID REFERENCES telegram_accounts (id) ON DELETE CASCADE;
ALTER TABLE posts ADD COLUMN status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'ready', 'scheduled', 'sending', 'sent', 'failed', 'cancelled'));

-- The user's text is stored WITHOUT the mandatory footer; the footer and the final message are generated by the server
-- every time (see app/posts/composer.py), so a later branding change reaches every stored draft.
CREATE UNIQUE INDEX posts_id_account_user_uq ON posts (id, account_id, user_id);
CREATE INDEX posts_user_idx ON posts (user_id, account_id, updated_at DESC);
CREATE UNIQUE INDEX telegram_groups_id_account_user_uq ON telegram_groups (id, account_id, user_id);

-- Target groups of a post. Only groups that are currently postable may be inserted by the application; the rows stay
-- when a group later stops being postable, and whoever sends (Step 6) must re-check every target at send time.
CREATE TABLE post_targets (
    post_id    UUID NOT NULL,
    group_id   UUID NOT NULL,
    account_id UUID NOT NULL,
    user_id    UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, group_id),
    FOREIGN KEY (post_id, account_id, user_id) REFERENCES posts (id, account_id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (group_id, account_id, user_id) REFERENCES telegram_groups (id, account_id, user_id) ON DELETE CASCADE
);
CREATE INDEX post_targets_group_idx ON post_targets (group_id);

-- Metadata of the (at most one) image of a post. The bytes live in the storage backend named here, under a random key
-- chosen at random, independent of the uploaded file name. The original file name is deliberately not stored.
CREATE TABLE post_media (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL,
    post_id         UUID NOT NULL,
    kind            TEXT NOT NULL DEFAULT 'image' CHECK (kind IN ('image')),
    content_type    TEXT NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png')),
    size_bytes      INTEGER NOT NULL CHECK (size_bytes > 0),
    width           INTEGER NOT NULL CHECK (width > 0),
    height          INTEGER NOT NULL CHECK (height > 0),
    sha256          TEXT NOT NULL,
    storage_backend TEXT NOT NULL CHECK (storage_backend IN ('database', 'local')),
    storage_key     TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, user_id),
    UNIQUE (post_id),
    UNIQUE (storage_backend, storage_key),
    FOREIGN KEY (post_id, user_id) REFERENCES posts (id, user_id) ON DELETE CASCADE
);

-- Bytes of the "database" storage backend (works on Render's free tier, where the web service's disk is not persistent).
-- Never read directly by a page: images are served only through the owner-checked /posts/{id}/image route.
CREATE TABLE media_blobs (
    storage_key  TEXT PRIMARY KEY,
    data         BYTEA NOT NULL,
    created_unix BIGINT NOT NULL
);
